# These are supported funding model platforms

github: [thagore-foundation]
patreon: #
open_collective: thagore-foundation
ko_fi: #
tidelift: #
community_bridge: 
liberapay: #
issuehunt: 
lfx_crowdfunding: 
polar: #
buy_me_a_coffee: #
thanks_dev: #
custom: ['https://opencollective.com/thagore-foundation']
