# These are supported funding model platforms

github: [thagore-foundation]
patreon: #
open_collective: #
ko_fi: lehungquangminh
tidelift: #
community_bridge: 
liberapay: #
issuehunt: 
lfx_crowdfunding: 
polar: #
buy_me_a_coffee: #
thanks_dev: #
custom: #
