[workspace]
members = [
    "crates/interpreter",
    "crates/module_graph",
    "crates/lexer",
    "crates/parser",
    "crates/ast",
    "crates/typeck",
    "crates/ir",
    "crates/codegen",
    "tools/thagore-cli",
    "tools/thagore-bench",
    "tools/thagore-lsp",
    "tools/thagore-fmt",
    "playground/wasm",
]
resolver = "2"

[profile.release.package.thagore-wasm]
opt-level = "z"
codegen-units = 1
